model:
  class_name: model.LVSM_scene_encoder_decoder.Images2LatentScene

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9  # 3 RGB + 3 direction + 3 Reference

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6  # 3 direction + 3 Reference
  transformer:
    d: 768
    d_head: 64
    encoder_n_layer: 8
    decoder_n_layer: 16
    special_init: true
    depth_init: true
    use_qk_norm: true
    n_latent_vectors: 3072 # 3x32x32

training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 32
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  center_crop: true
  scene_scale_factor: 1.35
  checkpoint_dir: ./experiments/checkpoints/LVSM_trellis
  checkpoint_every: 2000
  dataset_name: data.dataset_scene.Dataset
  dataset_path: /mnt/bn/robotic-sim-yekai/data/trellis_re10k_little_fix/train/full_list.txt
  dataset_split: 1.0
  grad_accum_steps: 1
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0
  l1_loss_weight: 0.0
  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.25

  lr: 0.0004
  train_steps: 100000
  num_input_views: 4
  num_target_views: 8
  num_threads: 8
  num_views: 12
  num_workers: 4

  prefetch_factor: 32
  print_every: 20




  square_crop: true
  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  view_selector:
    max_frame_dist: 192
    min_frame_dist: 25
  vis_every: 50
  wandb_exp_name: LVSM_trellis_test
  wandb_log_every: 50
  
  wandb_project: yekai.lvsm
  warmup: 3000
  weight_decay: 0.05


# inference / evaluation
inference:
  if_inference: False
  compute_metrics: False
  save_images: False
  view_idx_file_path: ./data/evaluation_index_re10k.json
  render_video: False
  render_video_config:
    traj_type: interpolate
    num_frames: 60
    loop_video: True 
    order_poses: False